name: Deb Build

on:
  repository_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Queue
        uses: ahmadnassri/action-workflow-queue@v1
      - name: Checkout ${{ github.event.client_payload.repository }}
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.client_payload.repository }}
          submodules: true
      - name: Build ${{ github.event.client_payload.repository }}
        uses: jtdor/build-deb-action@v1
        with:
          host-arch: arm64
          artifacts-dir: artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            artifacts/*.deb

  publish:
    name: Publish
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout apt repository
        uses: actions/checkout@v3
        with:
          ref: bookworm
          submodules: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Copy deb packages
        run: |
          mv artifacts/*/*.deb pool/main/
          rm -rf artifacts
      - name: Update and sign apt repository
        run: |
          homedir="$(pwd)"
          dpkg-scanpackages --arch arm64 pool/ > dists/bookworm/main/binary-arm64/Packages
          cat dists/bookworm/main/binary-arm64/Packages | gzip -9 > dists/bookworm/main/binary-arm64/Packages.gz
          cd dists/bookworm
          $homedir/generate-release.sh > Release
          gpg --default-key "nitan.marcel@protonmail.com" -abs -o - Release > Release.gpg
          gpg --default-key "nitan.marcel@protonmail.com" --clearsign -o - Release > InRelease
          cd $homedir
      - name: Push apt repository changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          author_name: Marcel Alexandru Nitan
          author_email: nitan.marcel@protonmail.com
          message: "Update packages"
          branch: "bookworm"
  cleanup_job:
    name: Cleanup
    needs: Publish
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Clean old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1

