name: Clickable Build

on:
  workflow_dispatch:

env:
  ORGANIZATION: miatoll-linux

jobs:
  build:
    strategy:
      matrix:
        package: ["droidian-adaptation-miatoll"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ matrix.package }}
        uses: actions/checkout@v3
        with:
          repository: $ORGANIZATION/${{ matrix.package }}
          submodules: true
      - name: Build $ORGANIZATION/${{ matrix.package }}
        uses: pi-top/debian-package-build-action@master
        with:
          target_architecture: arm64
          docker_image: debian:stable
          build_directory: artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: $ORGANIZATION_${{} matrix.package }}
          path: artifacts/*.deb